language: go
go:
- '1.10'
install: make install
script:
- make test
- make build
- mv $TRAVIS_BUILD_DIR/codedeploy/* $TRAVIS_BUILD_DIR/bin/
- cd $TRAVIS_BUILD_DIR/bin
- zip -r latest *
- mkdir -p dsource
- mv latest.zip dsource/latest.zip
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "$AWS_S3_BUCKET"
  region: "$AWS_REGION"
  skip_cleanup: true
  local_dir: dsource
  upload-dir: wildproxy
- provider: codedeploy
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "$AWS_S3_BUCKET"
  region: "$AWS_REGION"
  key: wildproxy/latest.zip
  bundle: zip
  application: wildproxy-dev-app
  deployment_group: wildproxy-dev-deployment-group
env:
  global:
  - secure: N0BqKlKBTrUnSQj8ueVaK1OrH2ni4hNjG/hCyWXW+uFppmM+zfKnPAnKzB5y23s1xeB1vJka1jvdD9xhv6qy+q61rontsp2WWY99xhPdzjskxNy4V3MSvIb/22pUaSRHSWbWBB+58fNm6cE7n2AS7IPYy0Mxo1cD9+LColVvqeOV1AhY8/8tzleOR4DzRDhOZs9AN0Gl/wse8C7g1Ut465h6wIzgvc8AoQI9UI/yfXkDclWWzzFbbyPxnwQN/2NVIH8EJ2PB2RuzDQ6sg/FZo1udXSrksow5S3nF3p41SjyBNPRv5JEgV5ZXfJ4nSz4z4O3++89BDp2RkKkhc2anma0DPlZfvfUFjWy6yPZDi1BTg7RG2iyGuWijP1Pz9+uGZC+xEE+ewV70iZx8B5PMwMYvSiCIZGjdwdVYKdISiP+dGbGV9xJ0KSq+fpoKfz2sLLcGFa+fOUJCDMmASSzbGGCf+Ibsc/v4e104HSBu7AAuQrN8/NJgTXpmnrOoIafkRFeU1l/kgOdwGDL3W2sga2BT0lLnt7mm1I9KILouUxrlXx7ibuomZ4R3t/k8jyztM9S/0/Io4tOe6V7ELHkHKyyl3yd+B2j6oKfRT6ZiTNp6kb8EVOkPPqdnOCO4D0QyD8JCQTIwhNqWhiOmYIu/gUhxcZSH9MbOVuXt3oqy01g=
  - secure: Xe0wvWxpxBP9A6toCiG/h4jOAdxPTQjuXz5CqAC0u9xVkXrwRD78CPsRTBUqfy0Qk6S/LHNsmIOjW1bb4spwgB1gRAoVuvC30koOlUv2N+y/3wbXffyEhKsI/0CnScgX2I75HdKLr1/WsFCuHhu5cqX4LEGjlWpexyOZ30A0Oihp+Z23qJNR0lL0qsHG473VK5ORwaEyK9fIxI8KcQOhw0LqtniNIHtqK54IAVhO9slA6iR2/k+vSITCk5ozagIvFbtlwgKY/4InC8waGtz5rtMwNzYf+JxNVDU9HAyvFmeo9VGhD0nX2iStCQFiiyVW3MrGI18brfynMzJUpq2AKIxlwpxuz1LQS3Cc4QB/M+Vwzq4thpIi+mjvVD3I+vlAYXoFogPBHRPFveBw9ePpg4D+b5qaFsrXboCxRu4E2Jf4FaeOKXxL1IiNEDs/HWMl3kUCXINGjGHiAMzYXqJK3PiTWfkUmURFe7uRBU6goTQjHaBZ3CCzdVYt5z34lLdJTkya28GB/gC3rUMRJNVsnpH36utipR9MB3rz0ZWDRFvZabjHL5axJUmOOlmUG5w3fFq1i4pWaJrXsBAWtqPcNoKH4as93oF3gXRrttWMTzRCecjCVu9Lk9ltl4iUpCCTt5LHszKwNLuy5Q6r2JHRbNKDOpjyE/v8hK+XCXzFUhI=
  - secure: AUATThT4JVSASoYC+FhH7S+6di3mZHzVx4E5MeqFP+u7O4loEltwo9xkUDa04x9PUWMBsHR26aBbuctmN71xS00cr9AIDfmFGtI+pGF/sQtVUtChAl2QQxyWBZOcXXS3OkmMiDZCzqTFKf3Eju4a4F7fvE9yss+yPL2guHtN4ezxDkw9YWPh3eXN//Mak0Aeye+grg++tYNJx9vDeC9PDsNzJeNsfPSsGiQKm+V4xdjodsFoTueqgp1BQWeB/g9FiUOtxwc4vCGrmHIORe/b+xjdHNj8GgOeRigf/KnOLRdyyGJCZqB9g6B3X0WgS4v6/AGsHcxGvxIKFDQCIt2soJmiAkUXMxUgL//8m4hn7Kw7ifAWESbYybeH7AjMKxto8dr9Jw0kP8jY75NoPu80IIVRSA5mOTYF4V7d8jhV+XoWMv/LcD7p77+14pwXdHLb1UNo/Yta8aCj46zBS9KPyLzgeh06GbVqaiOtltidK07b3hsmr6cVnHpVsN5I2EYbJ8PGNFVqfxN6JLt+CMJiIj8Q1Rg/tvRlJ+0uc+yp9wNxgFhMAOBwfdN3RX6PhDJiK0ZN8u2igxtab+aOOF2bvtJpWOWvJhfk1TB3fGqztoTwBvxSKNPTvFOVp+aF5STl7AmE12fRRcBhyyZnHnFxFPxFWGNcrN7RGHcq1ueWOcY=
  - secure: MLsUYkxmOrjhUYgNfOBKDI6mQaRYA8524qAvA+CX1c4ZX7A+6OalBoNhg+gFeVmxof1Sh6mydlbIZob0EUtVVankWx8KqZpn3G1JaMKXjk/St4DGys60Bt7he/aGs+Z6BEhpSiDZh7pgqFbXboXofDjH5NYVwOrhd346Dwn0QJoFvv6Qg0ZPAyq0AaQKpyrfQpuAMK6nXOEfll3md+fGXrOmjDXvdm4UMxPEWsR5+axgnDb4eDkg7H5xhVIg5Qkr2WKijbDTOUadI3po3YBzH2rmd4GowIPA8l4yDM81uTLVs65rQV+IUzPjg539ac5qUGjloNW/9CX7z/hIxj+H0BRf6VTLSJUKRNnsSsvz5opw+CM12T+nTuJ/eVtmap7UslXAy1CB0J0+rFsQr1gDxaWLE+8D/dhULWBz1OSojXFtu9sQRGpO24BBFirXFJMJbLFoYa8Orb9uMGdcchny39yn7xOganvk4o3q5IXMMkdj0slLn6oy/MHB+MgTS/CQYFXTWv3NpJVmnHJpOyY1VvSONwcG8ht0Mf19xeIz5SIxvHvmT3dTxb3QeIBS+BWJUp6WHB/KBv5U4ElX7MK0eSQPW/TIvnVTvMbiMIxcdT/cp8n/H/JcHYYVr0oJStF0QDBB6yPJVLrQ+bIxFPP54duPrqjZwoNZs7YExXnCbIU=
