language: go
go:
- '1.10'
install: make install
script:
- make test
- make build
- mv $TRAVIS_BUILD_DIR/build $TRAVIS_BUILD_DIR/bin/
- mv $TRAVIS_BUILD_DIR/codedeploy/* $TRAVIS_BUILD_DIR/bin/
- cd $TRAVIS_BUILD_DIR/bin
- zip -r $TRAVIS_COMMIT *
- mkdir -p dsource
- mv $TRAVIS_COMMIT.zip dsource/$TRAVIS_COMMIT.zip
deploy:
- provider: s3
  bucket: "$AWS_S3_BUCKET"
  skip_cleanup: true
  local_dir: dsource
  upload-dir: wildproxy
  on:
    branch: master
- provider: codedeploy
  bucket: "$AWS_S3_BUCKET"
  key: wildproxy/$TRAVIS_COMMIT.zip
  bundle: zip
  application: wildproxy-dev-app
  deployment_group: wildproxy-dev-deployment-group
  on:
    branch: master
notifications:
  slack:
    secure: w2hMQ70kZokb/LfbJRcpyf4sK2EmKdxWuu5tzJCwc4eoSbIOtfcjuskkhH6OLevOOypT8iS3cHYa0Eo0rAwtGEz19VLPCs/QWZoej1gjV9IRwMbXhJ+HeHeG/ySogTuaG5kqiGwkJKT7gzM1LXvBzQo6wzMUDh+N7HxPVI7hyO5Xg4BvEAZJIimUYphRUNOK0bK7YcdS7qntqZtBvT6w8iCqka6xBd0kRKTSfk84VfrJQEkA59q2z7OeBMCLpjwPib+GPkiRXG7ErfzH4h7qy4UfvnQjUx16p74Km+t1r1yccM0anT2csewGNX+QmsM7+/m8ft13c6f6Kv66akUWAb2eBC6R9zkrivfaNF6+Jo+lTkSTb7l2gjnHwYVYqxrTR82IrumVlloNWAOJU8V8kzSJTmVBfWUWYtV5xFrd6ZxaCgoJkqOe30e6j4cyN+3DtO2T8IlC9E/+cdUyPvgwK/f3Zi8HQihpRR9TiofrFxLBWrroz8DMqL0DU6sW5056yC0s+/a1GK/8NU3tn52ki6tvJjw6IuH/s+t4okMT80gR2EqSvivgkvMxlECNO5x/EupgsV2ezUzUrH1nfzEFy290P/F4xq1p8Afu/P7NjMe/AyBpW4Y2f3/2zasEDZH5O4yEKuJAVCIslc3RF+sLWFn5Cm7gYcJNeoE+iggjJi0=
