version: 0.0

os: linux
files:
   - source: /
     destination: /opt/app/wildproxy
permissions:
   - object: /opt/app/wildproxy
     pattern: "**"
     owner: wildproxy
     group: wildproxy
     mode: 755
hooks:
  BeforeInstall:
    - location: hooks/before_install.sh
  ApplicationStart:
    - location: hooks/application_start.sh
